[package]
name = "hello-wasi-cli"
version = "0.1.0"
edition = "2024"

[package.metadata.component]
package = "component:hello-wasi-cli"

[package.metadata.component.dependencies]

[dependencies]
wit-bindgen-rt = { version = "0.43.0", features = ["bitflags"] }
